### ISSUE TITLE
#1: Design The NavBar

### ISSUE THREAD

**Issue by samuel0kello** [OkelloSam21/tasty-food#1]
Use CSS to style the image

![Screenshot from 2023-07-03 09-59-44](https://github.com/OkelloSam21/tasty-food/assets/115361239/8303d2ea-bf7a-4fd5-85dd-cfa601eae488)

**Comment by TK-Kirui** [comment]
Ok, assign me this.

**Comment by samuel0kello** [comment]
> Ok, assign me this.

Assigned issue to you @TK-Kirui

**Comment by samuel0kello** [comment]
When you are done with your changes ensure you link you Pr with this issue

**Comment by MartinOtieno** [comment]
Can you assign me too in this

**Comment by samuel0kello** [comment]
closing this issue

**Comment by samuel0kello** [comment]
closing this issue
