### ISSUE TITLE
Add content to readme.md

### ISSUE THREAD

**Issue by Glorycs29** [OkelloSam21/tasty-food#11]

**Comment by samuel0kello** [comment]
you can work on this

**Comment by samuel0kello** [comment]
The readme should contain contribution guide.

**Comment by Glorycs29** [comment]
I have created a new file Contributing.md for the guidelines, I'll provide a link for this file in Readme file.

**Comment by samuel0kello** [comment]
This is okay

**Comment by samuel0kello** [comment]
Ensure you link your pr to this issue

**Comment by Glorycs29** [comment]
okay sure
