### ISSUE TITLE
docs: Readme should contain information about the website and more information like, link to contribution guidelines.

### ISSUE THREAD

**Issue by Glorycs29** [OkelloSam21/tasty-food#15]

**Comment by samuel0kello** [comment]
@Glorycs29 are you working on this?

**Comment by Glorycs29** [comment]
> @Glorycs29 are you working on this?

@OkelloSam21 reassign me

**Comment by samuel0kello** [comment]
@Glorycs29 I have assigned this issue to you

**Comment by Glorycs29** [comment]
okay, I'll work on it.

**Comment by samuel0kello** [comment]
@Glorycs29 can you reopen you pr 
I have not merged it

**Comment by samuel0kello** [comment]
this is issue is closed as done
